version: '3'
services:
  app:
    build: ./
    image: spring-webflux-demo:latest
    command: java -jar app.jar --spring.profiles.active=prod
    ports:
      - "8080:8080"
    links:
       - mongo
       - redis

  mongo:
    image: mongo:latest

  redis:
    image: redis:latest
    command: redis-server --requirepass xPwRXvRS7kdcFQMn9hXe8fNt8FUmP28CrvbpLpwP7H7uvJRMM9YLNvUk5T4x4TCc
