spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always

application:
  session:
    maxIdleDays: 7

---
spring:
  profiles: dev
  data:
    mongodb:
      database: dev
logging:
  level:
    org.springframework.data.mongodb: DEBUG

---
spring:
  profiles: prod
  data:
    mongodb:
      host: mongo
      database: prod
  redis:
    host: redis
    password: xPwRXvRS7kdcFQMn9hXe8fNt8FUmP28CrvbpLpwP7H7uvJRMM9YLNvUk5T4x4TCc
logging:
  level:
    root: WARN
