spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: 5L2Z5q2M@gmail.com
    password: WWbyza645KiVdsdK
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

application:
  session:
    maxIdleDays: 7

---
spring:
  profiles: dev
  data:
    mongodb:
      database: dev
logging:
  level:
    root: WARN
#    org.springframework.data.mongodb: DEBUG

---
spring:
  profiles: prod
  data:
    mongodb:
      host: mongo
      database: prod
  redis:
    host: redis
    password: xPwRXvRS7kdcFQMn9hXe8fNt8FUmP28CrvbpLpwP7H7uvJRMM9YLNvUk5T4x4TCc
logging:
  level:
    root: ERROR
